[package]

name = "hal-demo"
version = "0.1.0"
authors = [ "Herman J. Radtke III <herman@hermanradtke.com>" ]

[[bin]]

name = "hal-demo"
path = "src/main.rs"

[dependencies]
hal = "*"
nickel = "*"
nickel_macros = "*"
postgres = "*"
rustc-serialize = "*"
time = "*"
